### ISSUE TITLE
High Sierra Unrecognized

### ISSUE THREAD

**Issue by ieatnerds** [nim-lang/osinfo#6]
Mac OSX 10.13, AKA High Sierra is unrecognized by the POSIX module. Instead it is shown as 10.3 Panther.

**Comment by dom96** [comment]
Wanna make a PR? https://github.com/nim-lang/osinfo/blob/master/src/osinfo/posix.nim#L44 :)

**Comment by ieatnerds** [comment]
Made PR. Submitted.
